### ISSUE TITLE
PhD in Network Security and Privacy

### ISSUE THREAD

**Issue by sn275** [alxdavids/comp-sci-phd-contacts#1]
Shishir Nagaraja
Glasgow, UK
University of Strathclyde (Computing)
shishir.nagaraja@strath.ac.uk
Position: A fully funded PhD studentship is available in the area of Network Security and Privacy. The PhD topic is fairly flexible however applicants interested in working at the intersection of software engineering, control theory, network security, or communications theory are particularly welcome.
Students should be skilled programmers with an interest in the foundations of: statistics, distributed systems, and networks. Any UK or EU resident is eligible to apply. UK/EU citizenship is not required. The studentship is for 3.5 years, and includes tuition fees and a competitive stipend. Applicants should send complete applications including two academic references, research proposal, transcripts, and degree certificates via the Post Graduate Application Portal by 05 May 2018. See https://www.strath.ac.uk/courses/research/computerinformation
sciences/
Expiry date: 01 June 2018

**Comment by alxdavids** [comment]
Added
