### ISSUE TITLE
PhD studentship in Cyber Security

### ISSUE THREAD

**Issue by hooklee** [alxdavids/comp-sci-phd-contacts#10]
Contact name: Shujun Li
Location (city/country): Canterbury, UK
Institution (department): School of Computing, University of Kent
Contact information (email, telephone number etc.): S.J.Li@kent.ac.uk
Research areas of interest: Cyber Security, see https://www.cs.kent.ac.uk/research/studyingforaphd/phd-cybersecurity-2018.html for a list of topics
Positions available/funding opportunities: PhD in Cyber Security (for an UK/EU national)
Expiry date for opening: open until filled

**Comment by alxdavids** [comment]
Added, would you be able to inform us if the position is filled so that we can remove?
