### ISSUE TITLE
PhD studentship in Cloud and Device Data Protection

### ISSUE THREAD

**Issue by hooklee** [alxdavids/comp-sci-phd-contacts#11]
Contact name: Shujun Li
Location (city/country): Canterbury, UK and Munich, Germany
Institution (department): School of Computing, University of Kent and German Research Center in Munich, Huawei Technologies
Contact information (email, telephone number etc.): S.J.Li@kent.ac.uk
Research areas of interest: Cloud and Device Data Protection, see https://www.cs.kent.ac.uk/research/studyingforaphd/phd-cloud-protection.html for more details
Positions available/funding opportunities: PhD studentship in Cloud and Device Data Protection
Expiry date for opening: open until filled

**Comment by alxdavids** [comment]
Added, would you be able to inform us if the position is filled so that we can remove?
