### ISSUE TITLE
New job entry

### ISSUE THREAD

**Issue by hooklee** [alxdavids/comp-sci-phd-contacts#4]
Contact name: Shujun Li
Location (city/country): Canterbury, UK
Institution (department): Kent Interdisciplinary Research Centre in Cyber Security (KirCCS), University of Kent
Contact information (email, telephone number etc.): hooklee@gmail.com
Research areas of interest: Cyber Security
Positions available/funding opportunities: EPSRC funded PhD studentship, more details at https://cyber.kent.ac.uk/calls.html#PhDs
Expiry date for opening: Rolling deadline until 31st May 2018

**Comment by alxdavids** [comment]
Also added.
