### ISSUE TITLE
New job entry

### ISSUE THREAD

**Issue by hooklee** [alxdavids/comp-sci-phd-contacts#5]
Contact name: Shujun Li
Location (city/country): Canterbury, UK
Institution (department): Kent Interdisciplinary Research Centre in Cyber Security (KirCCS), University of Kent
Contact information (email, telephone number etc.): hooklee@gmail.com
Research areas of interest: Cyber Security
Positions available/funding opportunities: University funded PhD studentship, more details at http://www.hooklee.com/default.asp?t=Call%20for%20PhD%20Applications
Expiry date for opening: Available until filled

**Comment by alxdavids** [comment]
Thanks! and added (if you to make future edits then reopen this issue)
