### ISSUE TITLE
Research Associate in AI for Privacy Protection

### ISSUE THREAD

**Issue by hooklee** [alxdavids/comp-sci-phd-contacts#7]
Contact name: Shujun Li
Location (city/country): Canterbury, Kent, UK
Institution (department): University of Kent (School of Computing)
Contact information (email, telephone number etc.): hooklee@gmail.com, S.J.Li@kent.ac.uk, www.hooklee.com
Research areas of interest: AI for Privacy Protection
Positions available/funding opportunities: 3-year RA post, more details at https://www.jobs.ac.uk/job/BJU862/research-associate-in-ai-for-privacy-protection/
Expiry date for opening: application deadline 13th June 2018

**Comment by alxdavids** [comment]
added a7c016d83e31a157a83f187d1f465f45f9e9a903
