### ISSUE TITLE
Lecturer in Computer Science (Cyber Security and AI)

### ISSUE THREAD

**Issue by hooklee** [alxdavids/comp-sci-phd-contacts#9]
Contact name: Richard Jones
Location (city/country): Canterbury, UK
Institution (department): School of Computing, University of Kent
Contact information (email, telephone number etc.): cs-hos@kent.ac.uk
Research areas of interest: Cyber Security, AI, quantum computing
Positions available/funding opportunities: Lecturer in Computer Science (https://www.jobs.ac.uk/job/BLE293/lecturer-in-computer-science/)
Expiry date for opening: 15 August 2018

**Comment by alxdavids** [comment]
Added
